# Generated by Django 2.1.4 on 2018-12-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20181223_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='required',
            new_name='status',
        ),
    ]
