# Generated by Django 2.1.4 on 2018-12-24 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20181223_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionvalue',
            options={'verbose_name': 'Product option value', 'verbose_name_plural': 'Product option values'},
        ),
        migrations.AlterUniqueTogether(
            name='optionvalue',
            unique_together=set(),
        ),
    ]
